### ISSUE TITLE
Second meetup -- DevConf.CZ

### ISSUE THREAD

**Issue by igor-raits** [rust-brno/meetup#5]
We've got our own meetup on devconfcz, let's organize it for that time.

https://devconfcz2019.sched.com/event/K8RG/rust-meetup

**Comment by panstromek** [comment]
wait - so this meetup is canceled? I was about to come...

**Comment by panstromek** [comment]
I'd love to do both actually...

**Comment by igor-raits** [comment]
@panstromek no, I'm very sorry.

Meetup will happen this thursday (I just realized that it is BEFORE devconf and not AFTER).

Come on this thursday!

**Comment by panstromek** [comment]
ok, then.. nice ;)

**Comment by msehnout** [comment]
Please be aware, that you need tickets for DevConf. There is a limited amount of them, so come early if you don't have one already.

**Comment by igor-raits** [comment]
It has happened, closing.
